<?php
$translate = $this->plugin('translate');
if(empty($site)) {
    $this->form->setAttribute('action', $resource->url('delete'));
}
else {
    //Lesson Plan logic
    $this->form->setAttribute('action', $this->url(
        'admin/site/slug/lesson-plan/lesson_plan-id',
        [
            'controller' => 'lesson-plan',
            'action' => 'delete',
            'id' => $resource->id(),
            'site-slug' => $site->slug(),
        ]
    ));
}
$this->form->setButtonLabel('Confirm delete'); // @translate
?>
<?php if ($this->wrapSidebar): ?>
<div id="delete" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $translate('Close')]); 
    
    ?>
<?php endif; ?>
    <div id="sidebar-confirm">
        <?php $resourceLabel = $translate($this->resourceLabel);?>
        <h3><?php echo sprintf($translate('Delete %s'), $resourceLabel); ?></h3>
        <p><?php echo sprintf($translate('Are you sure you would like to delete this %s?'), $resourceLabel); ?></p>
        <?php echo $this->form($this->form); ?>
    </div>
<?php if ($this->wrapSidebar): ?>
</div>
<?php endif; ?>
