<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'add lesson-plans');
?>

<?php echo $this->pageTitle($translate('New Lesson Plan'), 1, $translate('Lesson Plans')); ?>
<?php $this->trigger('view.add.before'); ?>
<?php
echo $this->partial('omeka/admin/item/form.phtml', [
    'form' => $form,
    'item' => null,
    'mediaForms' => $mediaForms,
    'submitLabel' => $translate('Add'),
    'sectionNavEvent' => 'view.add.section_nav',
    'action' => 'add',
    'site' => $site,
    'itemSetDefault' => !empty($item_set_default) ? $item_set_default : null,
    'resourceTemplateDefault' => !empty($resource_template_default) ? $resource_template_default : false,
    'propertyDefault' => !empty($property_default) ? $property_default : false,
    'propertyTermDefault' => !empty($property_term_default) ? $property_term_default : false,
    'resourceTemplateLabelDefault' => !empty($resource_template_label_default) ? $resource_template_label_default : false,
]);
?>

<?php $this->trigger('view.add.after'); ?>
