<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
$form->prepare();
$this->htmlElement('body')->appendAttribute('class', 'add lesson-plans');
?>
<?php echo $this->pageTitle($translate('Configure Lesson Plans'), 1, $translate('Lesson Plans')); ?>


<?php echo $this->form()->openTag($form);?>
<input type="hidden" name="site_id" value="<?php echo $site->id();?>"/>
<div class="field">
<div class="field-meta"> <label>Set default Item Set for Lesson Plans: </label></div>
<div class="inputs">
    <select name="item_set_id">
    <option value="" disabled="disabled" <?php echo empty($item_set_id) ? "selected" : ""; ?>>Select Default Item Set for Lesson Plans</option>
    <?php foreach($itemSets as $itemSet):?>
    <option value="<?php echo $itemSet->id()?>" <?php echo !empty($item_set_id) && $item_set_id == $itemSet->id()? "selected" : ""; ?>><?php echo $itemSet->title() ." (". $itemSet->owner()->name() .")"?></option>
    <?php endforeach;?>
    </select>
    </div>
</div>

<?php $this->trigger('view.add.before'); ?>


<?php echo $formElement($form->get('csrf')); ?>
<div id="page-actions">

    <button type="submit" name="save-configuration-submit"><?php echo $escape("Save Configuration"); ?></button>
</div>
<?php $this->trigger('view.add.after'); ?>
<?php echo $this->form()->closeTag(); ?>