<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'edit lesson-plans');
$deleteButton = $item->userIsAllowed('delete')
    ? '<a href="#" class="delete button">' . $translate('Delete') . '</a>'
    : null;
?>

<script type='text/javascript'>
var valuesJson = <?php echo json_encode($item->values()); ?>;
</script>

<?php echo $this->pageTitle($item->displayTitle(), 1, $translate('Lesson Plans'), $translate('Edit')); ?>
<?php $this->trigger('view.edit.before'); ?>
<?php
echo $this->partial('omeka/admin/item/form.phtml', [
    'form' => $form,
    'item' => $item,
    'resource' => $resource,
    'mediaForms' => $mediaForms,
    'submitLabel' => $translate('Save'),
    'deleteButton' => $deleteButton,
    'sectionNavEvent' => 'view.edit.section_nav',
    'action' => 'edit',
    'resourceTemplateDefault' => !empty($resource_template_default) ? $resource_template_default : false,
    'propertyDefault' => !empty($property_default) ? $property_default : false,
    'propertyTermDefault' => !empty($property_term_default) ? $property_term_default : false,
    'resourceTemplateLabelDefault' => !empty($resource_template_label_default) ? $resource_template_label_default : false,
]);
?>

<?php echo $this->deleteConfirm($item, 'item', true, $this->site);?>

<?php $this->trigger('view.edit.after'); ?>
