<?php
$this->headScript()->appendFile($this->assetUrl('js/metadata-browse.js', 'MetadataBrowse'));
$this->headLink()->appendStylesheet($this->assetUrl('css/metadata-browse.css', 'MetadataBrowse'));
$this->htmlElement('body')->appendAttribute('class', 'sidebar-open');
?>


<?php echo $this->pageTitle($this->translate('Custom Search'), 1, $this->translate('Sites'), $this->translate('Settings')); ?>

